import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Typography from '@mui/material/Typography';

import { trpc } from "../utils/trpc";
import HomeCards from "../components/Cards/HomeCards";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Madeira Experience</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-[15%]">
        <HomeCards />
      </main>
    </>
  );
};

export default Home;


